### ISSUE TITLE
Higlight today?

### ISSUE THREAD

**Issue by mtnyvz16** [fengyuanchen/datepicker#28]
How can I highlight **today**?

**Comment by soomtong** [comment]
```css
.datepicker-panel>ul>li.picked, .datepicker-panel>ul>li.picked:hover {
    font-weight: bold;
    background: gray;
}
```

just change above selectors
